name: many
description: a package that listens to functions periodically.
version: 1.0.2
homepage: https://github.com/SPiercer/many

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  shared_preferences: ^2.0.13  
  
dev_dependencies:
  flutter_lints: ^1.0.0